export const SERVER_SPEAKING_URL = process.env.NEXT_PUBLIC_SERVER_SPEAKING_URL!
export const CLERK_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY!
export const CLERK_SECRET_KEY = process.env.CLERK_SECRET_KEY!
export const CLERK_SIGN_IN_URL = process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL!
export const CLERK_SIGN_UP_URL = process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL!
export const CLERK_AFTER_SIGN_IN_URL =
  process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL!
export const CLERK_AFTER_SIGN_UP_URL =
  process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL!
export const TINY_EDITOR_API_KEY = process.env.NEXT_PUBLIC_TINY_EDITOR_API_KEY!
