export const UNKNOWN_ERROR_MESSAGE =
  "An unknown error occurred. Please try again later."

export const practiceTest = {
  id: 2,
  testId: "878fb940-3f64-ef11-9838-d03c1f563019",
  testTitle: "IELTS Simulation Listening Test 1",
  duration: 2400,
  testType: "Listening",
  totalEngaged: 86188,
  totalQuestion: 40,
  totalSection: 4,
  createDate: "0001-01-01T00:00:00",
  modifiedDate: null,
  testCategoryId: 1,
  testCategory: null,
  tags: [],
  comments: [],
  testHistories: [],
  testSections: [
    {
      testSectionId: 1,
      testSectionName: "Recording 1",
      readingDesc: null,
      audioResourceUrl: "http://example.com/audio1.mp3",
      totalQuestion: 10,
      sectionTranscript: null,
      testSectionPartitions: [
        {
          testSectionPartId: 1,
          partitionDesc: "Description for questions",
          isVerticalLayout: false,
          partitionImage: null,
          partitionTagId: 1,
          partitionTag: null,
          questions: [
            {
              questionId: 1,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 1,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 1,
            },
            {
              questionId: 2,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 2,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 1,
            },
            {
              questionId: 3,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 3,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 1,
            },
            {
              questionId: 4,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 4,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 1,
            },
            {
              questionId: 5,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 5,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 1,
            },
            {
              questionId: 6,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 6,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 1,
            },
            {
              questionId: 7,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 7,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 1,
            },
            {
              questionId: 8,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 8,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 1,
            },
            {
              questionId: 9,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 9,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 1,
            },
            {
              questionId: 10,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 10,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 1,
            },
          ],
          testSectionId: 1,
        },
      ],
      testId: "00000000-0000-0000-0000-000000000000",
    },
    {
      testSectionId: 2,
      testSectionName: "Recording 2",
      readingDesc: null,
      audioResourceUrl: "http://example.com/audio2.mp3",
      totalQuestion: 10,
      sectionTranscript: null,
      testSectionPartitions: [
        {
          testSectionPartId: 2,
          partitionDesc: "Description for questions",
          isVerticalLayout: false,
          partitionImage: null,
          partitionTagId: 2,
          partitionTag: null,
          questions: [
            {
              questionId: 11,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 11,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 2,
            },
            {
              questionId: 12,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 12,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 2,
            },
            {
              questionId: 13,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 13,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 2,
            },
            {
              questionId: 14,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 14,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 2,
            },
            {
              questionId: 15,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 15,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 2,
            },
          ],
          testSectionId: 2,
        },
        {
          testSectionPartId: 3,
          partitionDesc: "Description for questions",
          isVerticalLayout: false,
          partitionImage: null,
          partitionTagId: 3,
          partitionTag: null,
          questions: [
            {
              questionId: 16,
              questionDesc: "Multiple Choice 1",
              questionAnswerExplanation: null,
              questionNumber: 16,
              isMultipleChoice: true,
              questionAnswers: [
                {
                  questionAnswerId: 21,
                  answerDisplay: null,
                  answerText: "A",
                  isTrue: true,
                  questionId: 16,
                },
                {
                  questionAnswerId: 22,
                  answerDisplay: null,
                  answerText: "B",
                  isTrue: false,
                  questionId: 16,
                },
                {
                  questionAnswerId: 23,
                  answerDisplay: null,
                  answerText: "C",
                  isTrue: false,
                  questionId: 16,
                },
              ],
              testSectionPartId: 3,
            },
            {
              questionId: 17,
              questionDesc: "Multiple Choice 2",
              questionAnswerExplanation: null,
              questionNumber: 17,
              isMultipleChoice: true,
              questionAnswers: [
                {
                  questionAnswerId: 24,
                  answerDisplay: null,
                  answerText: "A",
                  isTrue: false,
                  questionId: 17,
                },
                {
                  questionAnswerId: 25,
                  answerDisplay: null,
                  answerText: "B",
                  isTrue: true,
                  questionId: 17,
                },
                {
                  questionAnswerId: 26,
                  answerDisplay: null,
                  answerText: "C",
                  isTrue: false,
                  questionId: 17,
                },
              ],
              testSectionPartId: 3,
            },
            {
              questionId: 18,
              questionDesc: "Multiple Choice 3",
              questionAnswerExplanation: null,
              questionNumber: 18,
              isMultipleChoice: true,
              questionAnswers: [
                {
                  questionAnswerId: 27,
                  answerDisplay: null,
                  answerText: "A",
                  isTrue: false,
                  questionId: 18,
                },
                {
                  questionAnswerId: 28,
                  answerDisplay: null,
                  answerText: "B",
                  isTrue: false,
                  questionId: 18,
                },
                {
                  questionAnswerId: 29,
                  answerDisplay: null,
                  answerText: "C",
                  isTrue: true,
                  questionId: 18,
                },
              ],
              testSectionPartId: 3,
            },
            {
              questionId: 19,
              questionDesc: "Multiple Choice 3",
              questionAnswerExplanation: null,
              questionNumber: 19,
              isMultipleChoice: true,
              questionAnswers: [
                {
                  questionAnswerId: 30,
                  answerDisplay: null,
                  answerText: "A",
                  isTrue: false,
                  questionId: 19,
                },
                {
                  questionAnswerId: 31,
                  answerDisplay: null,
                  answerText: "B",
                  isTrue: false,
                  questionId: 19,
                },
                {
                  questionAnswerId: 32,
                  answerDisplay: null,
                  answerText: "C",
                  isTrue: true,
                  questionId: 19,
                },
              ],
              testSectionPartId: 3,
            },
            {
              questionId: 20,
              questionDesc: "Multiple Choice 3",
              questionAnswerExplanation: null,
              questionNumber: 20,
              isMultipleChoice: true,
              questionAnswers: [
                {
                  questionAnswerId: 33,
                  answerDisplay: null,
                  answerText: "A",
                  isTrue: false,
                  questionId: 20,
                },
                {
                  questionAnswerId: 34,
                  answerDisplay: null,
                  answerText: "B",
                  isTrue: false,
                  questionId: 20,
                },
                {
                  questionAnswerId: 35,
                  answerDisplay: null,
                  answerText: "C",
                  isTrue: true,
                  questionId: 20,
                },
              ],
              testSectionPartId: 3,
            },
          ],
          testSectionId: 2,
        },
      ],
      testId: "00000000-0000-0000-0000-000000000000",
    },
    {
      testSectionId: 3,
      testSectionName: "Recording 3",
      readingDesc: null,
      audioResourceUrl: "http://example.com/audio3.mp3",
      totalQuestion: 10,
      sectionTranscript: null,
      testSectionPartitions: [
        {
          testSectionPartId: 4,
          partitionDesc: "Description for questions",
          isVerticalLayout: false,
          partitionImage: null,
          partitionTagId: 4,
          partitionTag: null,
          questions: [
            {
              questionId: 21,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 21,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 4,
            },
            {
              questionId: 22,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 22,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 4,
            },
            {
              questionId: 23,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 23,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 4,
            },
            {
              questionId: 24,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 24,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 4,
            },
            {
              questionId: 25,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 25,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 4,
            },
          ],
          testSectionId: 3,
        },
        {
          testSectionPartId: 5,
          partitionDesc: "Description for questions",
          isVerticalLayout: false,
          partitionImage: null,
          partitionTagId: 5,
          partitionTag: null,
          questions: [
            {
              questionId: 26,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 26,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 5,
            },
            {
              questionId: 27,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 27,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 5,
            },
            {
              questionId: 28,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 28,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 5,
            },
            {
              questionId: 29,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 29,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 5,
            },
            {
              questionId: 30,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 30,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 5,
            },
          ],
          testSectionId: 3,
        },
      ],
      testId: "00000000-0000-0000-0000-000000000000",
    },
    {
      testSectionId: 4,
      testSectionName: "Recording 4",
      readingDesc: null,
      audioResourceUrl: "http://example.com/audio4.mp3",
      totalQuestion: 10,
      sectionTranscript: null,
      testSectionPartitions: [
        {
          testSectionPartId: 6,
          partitionDesc: "Description for questions",
          isVerticalLayout: false,
          partitionImage: null,
          partitionTagId: 6,
          partitionTag: null,
          questions: [
            {
              questionId: 31,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 31,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 6,
            },
            {
              questionId: 32,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 32,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 6,
            },
            {
              questionId: 33,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 33,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 6,
            },
            {
              questionId: 34,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 34,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 6,
            },
            {
              questionId: 35,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 35,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 6,
            },
          ],
          testSectionId: 4,
        },
        {
          testSectionPartId: 7,
          partitionDesc: "Description for questions",
          isVerticalLayout: false,
          partitionImage: null,
          partitionTagId: 7,
          partitionTag: null,
          questions: [
            {
              questionId: 36,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 36,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 7,
            },
            {
              questionId: 37,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 37,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 7,
            },
            {
              questionId: 38,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 38,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 7,
            },
            {
              questionId: 39,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 39,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 7,
            },
            {
              questionId: 40,
              questionDesc: null,
              questionAnswerExplanation: null,
              questionNumber: 40,
              isMultipleChoice: false,
              questionAnswers: null,
              testSectionPartId: 7,
            },
          ],
          testSectionId: 4,
        },
      ],
      testId: "00000000-0000-0000-0000-000000000000",
    },
  ],
} as const
