import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { viVN } from "@clerk/localizations"
import { ClerkProvider } from "@clerk/nextjs"
import { NextIntlClientProvider } from "next-intl"
import { getMessages } from "next-intl/server"

import ScreenOverlayLoading from "@/components/ui/screen-overplay-loading"
import { Toaster } from "@/components/ui/sonner"

import { ReactQueryProvider } from "./react-query-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Prep4IELTS",
  description: "Generated by create next app",
  icons: "/logo_sm.webp",
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const messages = await getMessages()

  return (
    <ClerkProvider
      localization={locale === "vi" ? viVN : undefined}
      appearance={{
        // baseTheme: actualTheme === "dark" ? dark : undefined,
        elements: {
          formButtonPrimary: "bg-primary text-primary-foreground !shadow-none",
        },
      }}
    >
      <html lang={locale}>
        <body className={inter.className}>
          <ReactQueryProvider>
            <NextIntlClientProvider messages={messages}>
              {children}
              <Toaster position="top-right" />
              <ScreenOverlayLoading />
            </NextIntlClientProvider>
          </ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
