import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { viVN } from "@clerk/localizations"
import { ClerkProvider } from "@clerk/nextjs"
import { NextIntlClientProvider } from "next-intl"
import { getMessages } from "next-intl/server"

import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "STUDY4",
  description: "Generated by create next app",
  icons: "/logo_sm.webp",
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const messages = await getMessages()

  return (
    <ClerkProvider localization={locale === "vi" ? viVN : undefined}>
      <html lang={locale}>
        <body className={inter.className}>
          <NextIntlClientProvider messages={messages}>
            {children}
            <Toaster position="top-right" />
          </NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
